### PR TITLE
Bug fix when passing multiple headers

### LINKED ISSUE #481: curl provider: array of multiple headers does not work
## Affected Puppet, Ruby, OS and module versions/distributions

- Module version: **6.1.0**

## How to reproduce (e.g Puppet code you use)

```puppet
  archive { "example.yml":
    path             => "/tmp/example.yml",
    source           => "https://github.com/examplefile.yml",
    extract_path     => /opt/new/dir,
    headers          => [
      'Accept: application/vnd.github.raw',
      "Authorization: Bearer ${github_token}",
    ],
    provider         => 'curl',
    cleanup          => false,
  }
```

## What are you seeing
Only the first `--header` flag is available at execution
`--header 'Accept: application/vnd.github.raw'`

## What behaviour did you expect instead
Repition of headers
`--header 'Accept: application/vnd.github.raw' --header 'Authorization: Bearer xxx_example_token'`

### PR DESCRIPTION
**Pull request by sprankle**
#### Pull Request (PR) description
Apprach allowss optional_switch to accept array of values and bulk assign to a flag

#### This Pull Request (PR) fixes the following issues
Fixes #481

### CODE REVIEW

**Comment by kenyon** [comment]
I think you should add a test to https://github.com/voxpupuli/puppet-archive/blob/master/spec/unit/puppet/provider/archive/curl_spec.rb which has multiple headers, in a separate PR, so that  we can see the failure, then fix the problem in this PR on top of the other PR, so that we can see the fix.

File: lib/puppet/provider/archive/ruby.rb [hunk 1]
```diff
@@ -259,7 +259,9 @@ def gs_download(path)
   end
 
   def optional_switch(value, option)
-    if value
+    if value.is_a?(Array)
+      value.map { |item| option.map { |flags| flags % item } }.flatten
+    elsif value
       option.map { |flags| flags % value }
```
Comment (kenyon) [inline lib/puppet/provider/archive/ruby.rb:265]: How about this to eliminate some code duplication:

```suggestion
    if value
      Array(value).map { |item| option.map { |flags| flags % item } }.flatten
```

Tests pass locally with that.

**Review by kenyon — APPROVED** [review]
LGTM, should get another review though since some of the code was my contribution.

**Review by bastelfreak — APPROVED** [review]
