### PR TITLE
Use `relative_require` in artifactory functions

### LINKED ISSUE #320: Could not autoload puppet/parser/functions/artifactory_sha1: no such file to load -- puppet_x/bodeco/util
Thats somehow annoying .. I cant progress with my work at the moment .. 

Whats wrong here ?

`
[root@qa5 disk2]# puppet agent -t --server puppet --environment cm
Info: Using configured environment 'cm'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/artifactory_sha1: no such file to load -- puppet_x/bodeco/util at /etc/puppetlabs/code/modules/archive/manifests/artifactory.pp:103:14 at /etc/puppetlabs/code/modules/our_application/manifests/deployer.pp:53 on node qa5
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
`

[root@qa5 disk2]# puppet agent --version
5.3.3

### PR DESCRIPTION
**Pull request by alexjfisher**
This doesn't seem to have been neccessary for all users and probably
depends on how puppetserver has `ruby-load-path` configured.
See https://tickets.puppetlabs.com/browse/SERVER-973?focusedCommentId=224547&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-224547

Requiring the library using an absolute path should help
https://tickets.puppetlabs.com/browse/SERVER-973?focusedCommentId=352751&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-352751

Note, any changes to util.rb will still result in horrible environment
isolation issues.  A full fix would involve implementing
@trevor-vaughan's complete metaprogramming solution documented here.
https://www.onyxpoint.com/fixing-the-client-side-of-multi-tenancy-in-the-puppet-server

util.rb is somewhat more complicated than the example demonstrated, so
I've left that well alone for now.

Fixes #320

### CODE REVIEW

File: lib/puppet_x/bodeco/util.rb [hunk 1]
```diff
@@ -14,7 +14,7 @@ def self.content(url, options = {})
       end
 
       #
-      # This allows you to use a puppet syntax for a file and return it's content.
+      # This allows you to use a puppet syntax for a file and return its content.
```
Comment (alexjfisher) [inline lib/puppet_x/bodeco/util.rb]: Couldn't help myself! ;)
